server:
  port: 8072

spring:
  application:
    name: "gatewayserver"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8060/realms/master/protocol/openid-connect/certs"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true #Try to uncomment it when there are no routes
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8071/eureka/"

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
  pattern:
    level: "%5p[${spring.application.name},%X{trace_id},%X{span_id}]"