server:
  port: 8090

spring:
  application:
    name: "booking"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8060/realms/master/protocol/openid-connect/certs"
  cloud:
    function:
      definition: deleteBookingsOfEvent;createEventHistory
    stream:
      bindings:
        deleteBookingsOfEvent-in-0:
          destination: bookings-of-event-deletion-trigger
          group: ${spring.application.name}
        createEventHistory-out-0:
          destination: create-event-history
        bookingQrCodeCreated-out-0:
          destination: bookingQrCodeCreated
      kafka:
        binder:
          brokers:
            - localhost:9092


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/

logging:
  pattern:
    level: "%5p[${spring.application.name},%X{trace_id},%X{span_id}]"