services:
  network-deploy-service:
    networks:
      - fastbook


  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m