services:
  keycloak:
    image: "quay.io/keycloak/keycloak:26.0.0"
    container_name: keycloak-ms
    ports:
      - "8060:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
    command: "start-dev"
    volumes:
      - keycloak_data:/opt/keycloak/data
    extends:
      file: common-config.yml
      service: network-deploy-service

  eurekaserver:
    image: "eurekaserver:v1"
    container_name: eurekaserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    extends:
      file: common-config.yml
      service: microservice-base-config

  gatewayserver:
    image: "gatewayserver:v1"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8071/eureka/"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
    depends_on:
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config

  events:
    image: "events:v1"
    container_name: events-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "event"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8071/eureka/"
    depends_on:
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config
networks:
  fastbook:
    driver: "bridge"

volumes:
  keycloak_data:
