CREATE TABLE IF NOT EXISTS events_history (
  id INT NOT NULL AUTO_INCREMENT,
  user_id VARCHAR(100) NOT NULL,
  event_id INT NOT NULL,
  history_type ENUM('EVENT_ORGANIZED', 'ATTENDED_EVENT','BOOKED_EVENT') NOT NULL
);