server:
  port: 9011

spring:
  application:
    name: "notifications"
  cloud:
    function:
      definition: eventCreated;sendEmail;bookingQrCodeCreated
    stream:
      bindings:
        eventCreated-in-0:
          destination: event-creation-trigger
        sendEmail-out-0:
          destination: email-notification
        bookingQrCodeCreated-in-0:
          destination: bookingQrCodeCreated
      kafka:
        binder:
          brokers:
            - localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/

logging:
  pattern:
    level: "%5p[${spring.application.name},%X{trace_id},%X{span_id}]"